### ISSUE TITLE
USER STORY: <Adjust quantity in cart>

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/cozy-garden#12]
As a **user** I can **adjust the quantity of my chosen items inside my cart** so that **make changes if needed before purchasing**

# Acceptance Criteria

* Acceptance Criteria 1: In the "cart" page give the user an option to increase or decrease the quantity of any item chosen
* Acceptance Criteria 2: Also add a remove button if the user wants to completely remove the item

# Tasks
- [ ] Build a quantity selector for the user to chose the number of items they want of the item
- [ ] Add an "update" button for any adjustments to be made
- [ ] Add a remove button
