### ISSUE TITLE
USER STORY: <Checkout>

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/cozy-garden#13]
As a **user** I can **go to the checkout page and view a summary of my order and add my details for the delivery** so that **review my order again and add my order details**

# Acceptance Criteria

* Acceptance Criteria 1: Have a summary of the order present to the user
* Acceptance Criteria 2: Have a form for the user to fill in for the delivery to be made
* Acceptance Criteria 3: Have the payment information section clearly visible and simple to fill in

# Tasks
- [ ] Add a summary of the order in the page
- [ ] Add form with some required fields to only accept order with complete information
- [ ] Have the payments field separated from other fields with clear information about what information is required
- [ ] Have a button to make the payment or to go back to the cart

**Comment by BjornRodin** [comment]
fixed issue with webhooks where it, after alot of research, ended up being an issue with the environment variables Which i had set incorrectly somehow.

This was something i found on Slack in the end to give a better guide about what was going on. Issue should now be solved.
https://docs.google.com/presentation/d/e/2PACX-1vTT8PiM5LaYlf3GzslsdNKOa3vlG2Zbg4ZnzwYCFGEXVedoxqGHE87x66O8bG7cVr7qfpfFcssXPfof/pub?start=false&loop=false&delayms=3000&slide=id.g9fca4424b2_0_99
