### ISSUE TITLE
USER STORY: <Navigation>

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/cozy-garden#20]
As a **user** I can **navigate the site easily** so that **I know where I can find certain things**

# Acceptance Criteria

* Acceptance Criteria 1: have a simple nav-bar with clear headers and content of what the user can expect when it is clicked
* Acceptance Criteria 2: Have a responsive design
* Acceptance Criteria 3:

# Tasks
- [ ] Make the navbar clear to understand with both its headers and the content within the headers
- [ ] Icons should be logical for what they are supposed to do
- [ ] Make the navbar responsive to work well even on small screens

**Comment by BjornRodin** [comment]
When testing the code i realized that "li" elements couldnt stand alone, they have to be wrapped. So in my case i wrapped them in a "ul" to handle the issue that was present.
