### ISSUE TITLE
USER STORY: <Login / Logout>

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/cozy-garden#6]
As a **user** I can **easily find where to login and logout** so that **I can login quickly aswell as logging out**

# Acceptance Criteria

* Acceptance Criteria 1: Have the login in the navbar to make it easy for the user to login
* Acceptance Criteria 2: When user is logged in the button should instead say "logout"
* Acceptance Criteria 3: Prompt the user with a message whenever they have logged in/out

# Tasks
- [ ] have the login in the navbar
- [ ] Make it so that the user when logged in instead see the logout button
- [ ] Give the user messages whenever they login or logout
