### ISSUE TITLE
USER STORY: <View Order History>

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/cozy-garden#8]
As a **user** I can **login to my profile and view my order history** so that **see what I have bought before**

# Acceptance Criteria

* Acceptance Criteria 1: On the user profile page the user should be able to view their order history

# Tasks
- [ ] Only logged in users can see their order history
- [ ] Show the order history
- [ ] Give user the ability to click on each order to view the complete order that was made
