### ISSUE TITLE
USER STORY: <Search Product>

### ISSUE THREAD

**Issue by BjornRodin** [BjornRodin/cozy-garden#9]
As a **user** I can **search for a specific product** so that **I can find it quickly**

# Acceptance Criteria

* Acceptance Criteria 1: have a searchbar 
* Acceptance Criteria 2: When user search for an item it will be shown to them
* Acceptance Criteria 3: If no items is found the user should get information that no products was found

# Tasks
- [ ] Add a searchbar to the site
- [ ] When search is made it will look into the database to find if there is anything matching with the search
- [ ] Show the item that was found or message that item was not found

**Comment by BjornRodin** [comment]
Searching the site works but i need to add products to make sure all is correct before this is done
